// Shape of /api/schedule/availability, shared by the server route and the
// browser cache. Nothing here imports server code, credentials or Luxon.
export interface TimeSlot {
  time: string // canonical start instant
  end: string // canonical end instant generated by the server
}
export type AvailabilitySlots = Record<string, TimeSlot[]>
export interface AvailabilityPayload {
  slots: AvailabilitySlots
  slotMinutes: number
}

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value)

/**
 * Narrows unknown JSON to a coherent payload. Anything malformed throws rather
 * than degrading to an empty calendar, so the form can show its retry and
 * email fallback instead of offering nothing or guessing a duration.
 */
export function parseAvailabilityPayload(data: unknown): AvailabilityPayload {
  if (!isRecord(data) || !isRecord(data.slots)) throw new Error('Invalid availability response')
  const slotMinutes = data.slotMinutes
  if (typeof slotMinutes !== 'number' || !Number.isInteger(slotMinutes) || slotMinutes <= 0) throw new Error('Invalid availability response')
  const slots: AvailabilitySlots = {}
  for (const [day, entries] of Object.entries(data.slots)) {
    if (!Array.isArray(entries)) throw new Error('Invalid availability response')
    slots[day] = entries.map(entry => {
      if (!isRecord(entry) || typeof entry.time !== 'string' || typeof entry.end !== 'string') throw new Error('Invalid availability response')
      const start = Date.parse(entry.time)
      const end = Date.parse(entry.end)
      if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start || end - start !== slotMinutes * 60_000) throw new Error('Invalid availability response')
      return { time: entry.time, end: entry.end }
    })
  }
  return { slots, slotMinutes }
}
